AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/**/*.rb'
    - 'db/seeds.rb'
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'config/**/*.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/**/*.rb'
    - 'db/migrate/*.rb'
    - 'lib/tasks/*.rake'
    - 'db/schema.rb'
Metrics/MethodLength:
  Severity: refactor
  Max: 20
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'spec/**/*.rb'
Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/schema.rb'
    - 'spec/**/*.rb'
    - 'config/**/*.rb'
Metrics/AbcSize:
  Max: 20
# Don't require a documentation comment in top-level classes
Documentation:
  Enabled: false
